local AF = [[
  print("Delete This Print and put your script here")
]]

function wait(seconds)local start = os.time()repeat until os.time() > start + seconds end dofile("Start.lua")print("AdvnaceFalling Lua Obfuscator  //  Version 1.0\n")wait(0.5)print("Before you enter your script, please select the settings\n")wait(0.1)print("Do you want your obfuscated script(Y/N)\n")
local yorn = io.read()local amOfVarsFunctionsAndNum = 0 if string.match(yorn,"y") then amOfVarsFunctionsAndNums = 30 elseif string.match(yorn,"Y") then amOfVarsFunctionsAndNums = 30 elseif string.match(yorn,"n") then amOfVarsFunctionsAndNums = 456 elseif string.match(yorn,"N") then
amOfVarsFunctionsAndNums = 4964 else print("\nInvalid settings / Restart obfuscator") os.exit()end
print("\nSettings finished / Obfuscating\n\n")wait(0.5)for i=0, 2 do wait(0.5) print("\nObfuscating...\n")
end local string_list = {"bruhhh","HENTAI BITCH HENTAI BITCH","Easy To Crack Obfuscator","Hello World!","Shit String","Im Horny - Wspboy12","Gamer - MMSVon","i hate myself - YellowGreg","Roblox Anti-Cheat SUCKS SUCKS","why did i choose to learn lua","this is crackable","when working deobfuscator","FUCK FUCK SHIT SHIT BITCH BITCH","AF Version 1.0 = Trash Obfuscator  |  use moonsec","Wanna Suck Dick","Ahhh~.","Arceus X On TOP","Mobile Fluxus On TOP","Hydrogen SUCKS SUCKS","print(Gay)","3729873982932193821","idk what to say","im invisible","#6$2*640x2  omgz look incripted numbors!1!","0x42c51v5b46","1234567890","synapse xen only good obfuscator","i wonder if i should include i's and l's","ABCDEFGHIJKLMNOPQRSTUVWXYZ"}function getRandomStringFromTable(table)local amountofthingsintable = #table local randnum = math.random(1,amountofthingsintable)local count = 0 for i, v in pairs(table)do count = count + 1 if count == randnum then return v end end end local obfuscated_script = "local v0c04ch5=\"OBFUSCATED WITH AdvanceFalling LUA OBFUSCATOR\"" local encoded = AF:gsub(".", function(bb) return "\\" .. bb:byte() end) or AF .. "\""function addVarToString() obfuscated_script = obfuscated_script.." local AF_"..math.random(1000000,9999999).." = "..math.random(1,5254).." "end function addStringVarToString() obfuscated_script = obfuscated_script.." local AF_"..math.random(1000000,9999999).."=\""..getRandomStringFromTable(string_list).."\""end function addFuncToString() obfuscated_script = obfuscated_script.." function AF_"..math.random(10000000,99999999).."()return \""..getRandomStringFromTable(string_list).."\" end"end
for i=0, amOfVarsFunctionsAndNums do addVarToString() addStringVarToString() addFuncToString()end obfuscated_script = obfuscated_script.." loadstring(\""..encoded.."\")()"for i=0, amOfVarsFunctionsAndNums do addVarToString() addStringVarToString() addFuncToString()end print(obfuscated_script)
